# Generated by Django 6.0.2 on 2026-02-11 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('stk_initiate', 'STK Push Initiated'), ('stk_timeout', 'STK Push Timed Out'), ('user_cancel', 'User Cancelled'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('payment_pending', 'Payment Pending')], max_length=20)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('response_code', models.CharField(blank=True, max_length=10)),
                ('response_description', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='orders.order')),
            ],
            options={
                'db_table': 'payments_transaction_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='payments_tr_order_i_7240f1_idx'), models.Index(fields=['checkout_request_id'], name='payments_tr_checkou_b943b4_idx'), models.Index(fields=['transaction_type'], name='payments_tr_transac_1ad103_idx'), models.Index(fields=['created_at'], name='payments_tr_created_f3559e_idx')],
            },
        ),
    ]
