# Generated by Django 6.0.2 on 2026-02-11 08:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Nyumbani (Home)'), ('work', 'Kazi (Work)'), ('other', 'Nyingine (Other)')], default='home', max_length=20)),
                ('label', models.CharField(help_text='Display name for address', max_length=100)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^(\\+?254|0)?[1-9]\\d{1,9}$')])),
                ('is_default', models.BooleanField(default=False, help_text='Use as default delivery address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_saved_address',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_default'], name='users_saved_user_id_1472e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SavedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='e.g., Toyota, Nissan', max_length=50)),
                ('model', models.CharField(help_text='e.g., Corolla, Altima', max_length=100)),
                ('year', models.IntegerField(help_text='Manufacturing year')),
                ('nickname', models.CharField(blank=True, help_text='e.g., My Home Car', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary vehicle for quick filter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_saved_vehicle',
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_primary'], name='users_saved_user_id_cf1091_idx')],
                'unique_together': {('user', 'make', 'model', 'year')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False, help_text='Only one user should have this enabled in production.')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Namba ya simu si sahihi. (Invalid phone number format.)', regex='^(\\+?254|0)?[1-9]\\d{1,9}$')])),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('business_registration', models.CharField(blank=True, help_text='Store registration number', max_length=50)),
                ('tax_id', models.CharField(blank=True, help_text='KRA PIN or similar', max_length=50)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'users_profile',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_owner'], name='users_profi_is_owne_3cd5d2_idx'), models.Index(fields=['created_at'], name='users_profi_created_f60c54_idx')],
            },
        ),
    ]
