# Generated by Django 6.0.2 on 2026-02-11 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vehicle manufacturer name', max_length=100, unique=True)),
                ('country', models.CharField(blank=True, help_text='Country of origin (e.g., Japan, South Korea)', max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vehicles_make',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='vehicles_ma_name_3d4fe8_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year_from', models.IntegerField(help_text='Start production year')),
                ('year_to', models.IntegerField(help_text='End production year')),
                ('engine_type', models.CharField(blank=True, help_text='e.g., 1.6L Petrol, 2.0L Diesel', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclemake')),
            ],
            options={
                'db_table': 'vehicles_model',
                'ordering': ['make__name', 'name', '-year_from'],
                'indexes': [models.Index(fields=['make', 'name'], name='vehicles_mo_make_id_eb04f3_idx'), models.Index(fields=['year_from', 'year_to'], name='vehicles_mo_year_fr_ab03d3_idx')],
                'unique_together': {('make', 'name', 'year_from', 'year_to')},
            },
        ),
    ]
